### ISSUE TITLE
the basic example is missing its Rproj file

### ISSUE THREAD

**Issue by opetchey** [Exp-Micro-Ecol-Hub/emeScheme#20]
From the manual:

The `basic` folder contains:

* An R-project file `expt1.Rproj`

**Comment by opetchey** [comment]
Also rename spreadsheet to `expt1 emeScheme.xlsx` as described in user manual.

**Comment by rkrug** [comment]
And commit 
https://github.com/Exp-Micro-Ecol-Hub/emeScheme/commit/e50e2e63a7a8a01d16a51bd997a660aad5baef6a
