### ISSUE TITLE
why .Rmd and .r in the code folder of basic example?

### ISSUE THREAD

**Issue by opetchey** [Exp-Micro-Ecol-Hub/emeScheme#21]
If at all possible remove the .r version. (as these are redundant and are not currently mentioned in the user manual)

**Comment by rkrug** [comment]
I added these to take a step away from RStudio, so that R-console users also have the code at hand and can execute it easily. I thought I had added this to the user manual?
But I can easily remove them.

**Comment by rkrug** [comment]
The text in the user manual reads:

> If you want to try it, delete all the files in the `data/archiving_data` foilder and knit the `data_preparation.Rmd` or execute / source the `data_preparation.R` file which will re-create the files in the `archiving_data` folder.

The R file is generated in the make_example command, so I can easily disable it.

**Comment by rkrug** [comment]
Left there as auto-generated from Rmd. so no additional maintenance
